data_root: ./data/version_2
marker_mapping: # can be used as CEA: all or CEA: CEA&SCCA. You can comment a marker to disable it
  CEA: ALL
  CYFRA21: ALL
  SCCA: ALL
  NSE: ALL
  ProGRP: ALL
  CA125: ALL
  EGFR: ALL
  IDH1: ALL
  CGA: ALL
  TTF1: ALL
  SYN: ALL
  CD56: ALL
  TPA: ALL
features:
  #  - Ct1
  #  - Ct2
  #  - GAPDH1
  #  - GAPDH2
  #  - GAPDHmean
  #  - ΔCt 1
  #  - ΔCt 2
  #  - ΔΔCt 1
  #  - ΔΔCt 2
  #  - Fold 1
  #  - Fold 2
  - Ave Fold
  - sd
class_mapping: # You can comment a class to disable it
  0: 1
  1: 0
  2: 0
  3: 0
  #  4: 4
  5: 0
num_split_fold: 3  # num-fold strategy to split train and eval dataset
num_repeat_split_fold: 30  # for RepeatedKFold
split_random_seed: 0.1
# if None, only use the samples that has all markers. or set the default value.
default_missing_value: null

model: gradient_boost
model_kwargs:
  learning_rate: [ 0.00001, 0.0001, 0.01 ]
  n_estimators: [ 100, 300 ]
  subsample: [ 0.3, 0.5, 0.8 ]
  max_depth: [ 1, 2, 3 ]
  random_state: [ 1 ]
  max_features: [ auto, null, 6 ]
