data_root: ./data/version_2
marker_mapping: # can be used as CEA: all or CEA: CEA&SCCA. You can comment a marker to disable it
  CEA: ALL
  CYFRA21: ALL
  SCCA: ALL
  NSE: ALL
  ProGRP: ALL
  CA125: ALL
  EGFR: ALL
  IDH1: ALL
  CGA: ALL
  TTF1: ALL
  SYN: ALL
  CD56: ALL
  TPA: ALL
#  CEA: ALL
#  CYFRA21: ALL
#  SCCA: ALL
#  NSE: ALL
#  GRP: ALL
#  CA125: ALL
#  EGFR: ALL
#  IDH1: ALL
features:
  #  - Ct1
  #  - Ct2
  #  - GAPDH1
  #  - GAPDH2
  #  - GAPDHmean
  #  - ΔCt 1
  #  - ΔCt 2
  #  - ΔΔCt 1
  #  - ΔΔCt 2
  #  - Fold 1
  #  - Fold 2
  - Ave Fold
  - sd
class_mapping: # You can comment a class to disable it
  0: 0
  1: 0
  2: 1
  3: 0
  #  4: 0
  5: 0
num_split_fold: 3  # num-fold strategy to split train and eval dataset
num_repeat_split_fold: 30  # for RepeatedKFold
split_random_seed: 0.2
# if None, only use the samples that has all markers. or set the default value.
default_missing_value: null
num_samples_in_each_bag: 1  # samples: original sample study. bag: model input with the same class

model: decision_tree
model_kwargs:
  criterion: [ gini, entropy ]
  splitter: [ best, random ]
  max_depth: [ 10, 100, null ]
  random_state: [ 1 ]
  class_weight: [ balanced ]

