data_root: ./data/version_2
marker_mapping:
  CEA: ALL
  CYFRA21: ALL
  SCCA: ALL
  NSE: ALL
  ProGRP: ALL
  CA125: ALL
  EGFR: ALL
  IDH1: ALL
  CGA: ALL
  TTF1: ALL
  SYN: ALL
  CD56: ALL
  TPA: ALL
features:
  - Ave Fold
  - sd
class_mapping:
  0: 1
  1: 0
  2: 0
  3: 0
  5: 0
feature_selection:
  method: RFE
  kwargs_search:
    n_features_to_select:
      - 1
      - 3
      - 5
      - 7
      - 9
      - 11
      - 13
      - 15
      - 17
      - 19
      - 21
      - 23
      - 25
feature_transformation:
  method: lmnn
  kwargs_search:
    n_components:
      - null
      - 3
      - 5
    init:
      - pca
      - lda
      - identity
    k:
      - 1
      - 3
      - 5
num_split_fold: 3
num_repeat_split_fold: 30
split_random_seed: 0.2
default_missing_value: null
num_samples_in_each_bag: 1
model: svm
model_kwargs:
  probability: true
  random_state: 1
model_kwargs_search:
  kernel:
    - linear
    - poly
    - rbf
    - sigmoid
  C:
    - 5.0e-05
    - 0.0001
    - 0.001
    - 0.01
    - 0.1
    - 1
    - 10
  class_weight:
    - balanced
