data_root: ./data/version_2
marker_mapping:
  CEA: ALL
  CYFRA21: ALL
  SCCA: ALL
  NSE: ALL
  ProGRP: ALL
  CA125: ALL
  EGFR: ALL
  IDH1: ALL
  CGA: ALL
  TTF1: ALL
  SYN: ALL
  CD56: ALL
  TPA: ALL
features:
  - Ave Fold
  - sd
class_mapping:
  0: 0
  1: 0
  2: 1
  3: 0
  5: 0
feature_selection:
  method: RFE
  kwargs_search:
    n_features_to_select:
      - 7
feature_transformation:
  method: lmnn
  kwargs_search:
    n_components:
      - 3
    init:
      - pca
    k:
      - 5
num_split_fold: 3
num_repeat_split_fold: 30
split_random_seed: 0.2
default_missing_value: null
num_samples_in_each_bag: 1
model: svm
model_kwargs:
  probability: true
  random_state: 1
  class_weight: balanced
model_kwargs_search:
  kernel:
    - linear
    - rbf
  C:
    - 5.0e-05
    - 0.01
    - 1
    - 10
